from .auth import router as auth_router
from .register import router as register_router
from .clothing_items import router as clothing_items_router
from .liked_clothes import router as liked_clothes_router
from .feeds import router as feeds_router
from .comments import router as comments_router
from .profile import router as user_profile_router
from .person_images import router as person_images_router
from .user_clothes import router as user_clothes_router