version: "3.8"

services:
  # FastAPI 백엔드 서비스
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=capstone
    depends_on:
      - mysql

  # React 프론트엔드 서비스
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  # MySQL 데이터베이스 서비스
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: capstone
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

# 데이터베이스 볼륨 정의
volumes:
  mysql-data:
